### ISSUE TITLE
Fix `maintainScrollVisibility` method, to fix 'property of undefined' error

### ISSUE THREAD

**Issue by jackkoppa** [politico/vue-accessible-selects#70]
Just copying over an error from one of our Sentry instances; looks like we'll just need an existence check:

```shell
TypeError: Cannot read property 'offsetHeight' of undefined
  at maintainScrollVisibility (./node_modules/@politico/vue-accessible-selects/dist/index.js:153:38)
  at call (./node_modules/@politico/vue-accessible-selects/dist/index.js:586:13)
  at invokeWithErrorHandling (./node_modules/vue/dist/vue.runtime.esm.js:1854:57)
  at callHook (./node_modules/vue/dist/vue.runtime.esm.js:4219:7)
  at callUpdatedHooks (./node_modules/vue/dist/vue.runtime.esm.js:4351:7)
```

**Comment by jackkoppa** [comment]
Whooo! Good to close after #82 & [v0.13.1](https://github.com/politico/vue-accessible-selects/releases/tag/v0.13.1), right @ikniaziuk?

**Comment by ikniaziuk** [comment]
yep. https://github.com/politico/vue-accessible-selects/pull/82 have to fix this
